FROM node:13

WORKDIR /instacar

EXPOSE 3000 8080

COPY . /instacar
ENV PATH /app/node_modules/.bin:$PATH
ENV API_PORT 3000
ENV APP_UUID 544f3457-3bab-464c-a6f3-086d0cc67913
ENV VUE_APP_APIENDPOINT http://localhost:3000/api
ENV VUE_APP_LINKENDPOINT http://localhost:3000/
ENV MONGODB_URL 15.206.167.181
ENV MONGODB_PORT 27017
ENV MONGODB_USER instaclient
ENV MONGODB_PASSWORD Admin@123
ENV MONGODB_AUTH_DB admin
ENV MONGODB_DB instaurl
ENV JWT_EXP 1h

RUN npm install @vue/cli -g
RUN npm install http-server -g
RUN npm install
RUN npm run build
CMD ["http-server", "dist"]